%%
%Perdictor Selection
PSt = ["Total Magnetic Intensity"...
    "Magneitc - 1VD"...
    "Magneitc - AS"...
    "Total Count" ...
    "Magneitc - HD"...
    "Gravity" ...
    "Gravity - 1VD" ...
    "Gravity - AS" ...
    "Gravity - HD" ...
    "MagMM" ...
    "VD1MM" ...
    "TCMM" ...
    "ASMM" ...
    "HDMM" ...
    "GravMM" ...
    "MagMN" ...
    "VD1MN" ...
    "TCMN" ...
    "ASMN" ...
    "HDMN" ...
    "GravMN" ...
    "MagMG" ...
    "VD1MG" ...
    "TCMG" ...
    "ASMG" ...
    "HDMG" ...
    "GravMG" ...
    "R_MagMM" ...
    "R_VD1MM" ...
    "R_TCMM" ...
    "R_ASMM" ...
    "R_HDMM" ...
    "R_GravMM" ...
    "R_MagMN" ...
    "R_VD1MN" ...
    "R_TCMN" ...
    "R_ASMN" ...
    "R_HDMN" ...
    "R_GravMN" ...
    "R_MagMG" ...
    "R_VD1MG" ...
    "R_TCMG" ...
    "R_ASMG" ...
    "R_HDMG" ...
    "R_GravMG" ...
    "TPMagM" ...
    "TPVD1M" ...
    "TPTCM" ...
    "TPASM" ...
    "TPHDM" ...
    "TPGravM" ...
    "Elevation"...
    "ΔZ"];

[idx,scores] = fscchi2(CSTest(:,1:size(CSTest,2)-1),string(CSTest(:,size(CSTest,2))));
idxInf = find(isinf(scores))

bar(scores(idx));
xlabel('Predictor rank');
ylabel('Predictor importance score');
title('Univariate feature ranking for classification using chi-square tests')
hold on
bar(scores(idx(length(idxInf)+1))*ones(length(idxInf),1))
legend('Finite Scores','Inf Scores')
hold off
baseFileName = sprintf('Chi-square.png');
ax = gca;
exportgraphics(ax,baseFileName,'BackgroundColor','none');

t = array2table(PSt(idx)');
%fig = uifigure;
%uit = uitable(fig,"Data",t,'ColumnName', "Reference Map");
%baseFileName = sprintf('Chi-square-Legend.png');
%exportapp(fig,baseFileName);
baseFileName = sprintf("Chi-square-Legend.csv");
writetable(t,baseFileName)

[idx,scores] = fscmrmr(CSTest(:,1:size(CSTest,2)-1),string(CSTest(:,size(CSTest,2))));
find(isinf(scores))

bar(scores(idx));
xlabel('Predictor rank');
ylabel('Predictor importance score');
title('Univariate feature ranking for classification using MRMR tests')
baseFileName = sprintf('MRMR.png');
ax = gca;
exportgraphics(ax,baseFileName,'BackgroundColor','none');

t = array2table(PSt(idx)');
baseFileName = sprintf('MRMR-Legend.csv');
writetable(t,baseFileName);

[idx,scores] = relieff(CSTest(:,1:size(CSTest,2)-1),string(CSTest(:,size(CSTest,2))),10);
find(isinf(scores))

bar(scores(idx));
xlabel('Predictor rank');
ylabel('Predictor importance score');
title('Rank importance of predictors using ReliefF')
baseFileName = sprintf('ReliefF.png');
ax = gca;
exportgraphics(ax,baseFileName,'BackgroundColor','none');

t = array2table(PSt(idx)');
baseFileName = sprintf('ReliefF-Legend.csv');
writetable(t,baseFileName);
